##format windshield survery data for downstream analysis.##
  ##1. from .shp polygons generated by REU students, extract needed info (centroid coords, date, Tillage, Residue, CoverCrop, etc). Combine all sites into a single dataframe and write output.
  ##2. create point .shp file of all observations.-- will end up overwriting this with 'shift_pts.R' code when sample locations are moved closer to road

library(rgdal)
library(raster)
library(rgeos)
library(sf)
library(stringr)
############################################################################################################
###########format windshield survey data for downstream processing##########################################
############################################################################################################
# Transect data (ground truth) over several counties in Indiana that tell us cover crop presence/absence in addition to cover crop type over several fields. 
#Specifically we have data for 5 counties: 
#Posey County (Fall 2015, Fall 2016, Spring 2017)
#Benton County (Fall 2014, Fall 2015, Fall 2016, Spring 2017)
#Warren County (Fall 2014, Fall 2015, Fall 2016, Spring 2017)
#White County (Fall 2014, Fall 2015, Fall 2016, Spring 2017)
#Gibson County (Fall 2015, Fall 2016, Spring 2017)

#write function to format Posey county data into format needed for appEEARS data download
#for Benton, Gibson, Posey, Warren, and White
format_posey <-function(county){
  files <- list.files(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, sep="/"), pattern = "\\_Join.shp$")

  all <- data.frame()
    for (i in files){
    print(paste("now processing ",substr(i, 7, 16), sep=""))
    tst <- as.data.frame(shapefile(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, i, sep="/")))
    if (substr(i, 7, 12) == "Spring"){
      #tst <- tst[,c(1:13, 16:18, 21,22)]
      tst <- tst[,c(4:7, 22, 21, 13, 16, 17, 18)]
      date <- sub(".*[_]([^.]+)[_].*", "\\1", i)
      tst$date <- rep(date, nrow= nrow(tst))
      tst$CC_Quality <- NA
      names(tst)[names(tst) == "coords.x2"] <- "R_Lat"
      names(tst)[names(tst) == "coords.x1"] <- "R_Lon"
      
    } else {
      #tst <- tst[,c(1:13, 15:18, 20, 21)]
      tst <- tst[,c(4:7, 21, 20, 13, 15:18)]
      names(tst)[names(tst) == "Fall_Tilla"] <- "Tillage"
      names(tst)[names(tst) == "coords.x2"] <- "R_Lat"
      names(tst)[names(tst) == "coords.x1"] <- "R_Lon"
      date <- sub(".*[_]([^.]+)[_].*", "\\1", i) #get the date of the observations
      tst$date <- rep(date, nrow= nrow(tst))
    }
    all <- rbind.data.frame(all, tst)
  }
  #all <- all[all$R_Lon != 0,] #get rid of the observations from the right side of the road
  all$site <- rep(county, nrow=nrow(all))
  print(head(all))
  #xy <- all[,c(9,8)]
  #print(all(xy))
  #spdf <- SpatialPointsDataFrame(coords=xy, data=all, proj4string=CRS("+proj=longlat +datum=WGS84 +no_defs"))
  #return(as.list(c(xy, spdf)))
  return(all)
}

#run the format_posey function on the Posey county files
Posey <- format_posey("Posey")
#remove unwanted columns (comment, L_Lon, L_Lat, coords.x1, coords.x2)
#Posey <- Posey[,-c(3,11,12,17,18)]

#write function to format Benton county data into format needed for appEEARS data download
format_benton <-function(county){
  files <- list.files(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, sep="/"), pattern = "\\_join.shp$")
  all <- data.frame()
  for (i in files){
    print(paste("now processing ",substr(i, 7, 16), sep=""))
    tst <- as.data.frame(shapefile(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, i, sep="/")))
    tst.shp <- shapefile(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, i, sep="/"))
    centers <- as.data.frame(gCentroid(tst.shp, byid = TRUE))
    tst <- cbind.data.frame(tst, centers)
    if (substr(i, 8, 13) == "Spring"){
      #tst <- tst[,c(1:9, 12, 15:17)]
      tst <- tst[,c(3:6, 21, 20, 12, 15:17)]
      names(tst)[names(tst) == "y"] <- "R_Lat"
      names(tst)[names(tst) == "x"] <- "R_Lon"
      date <- sub(".*[_]([^.]+)[_].*", "\\1", i)
      tst$date <- rep(date, nrow= nrow(tst))
      tst$CC_Quality <- NA
    } else {
      #tst <- tst[,c(1:9, 12, 14:17)]
      tst <- tst[,c(3:6, 19, 20, 12, 14:17)]
      names(tst)[names(tst) == "y"] <- "R_Lat"
      names(tst)[names(tst) == "x"] <- "R_Lon"
      names(tst)[names(tst) == "Fall_Tilla"] <- "Tillage"
      date <- sub(".*[_]([^.]+)[_].*", "\\1", i) #get the date of the observations
      tst$date <- rep(date, nrow= nrow(tst))
    }
    all <- rbind.data.frame(all, tst)
  }
  #all <- all[all$R_Lon != 0,]
  all$site <- rep(county, nrow=nrow(all))
  print(head(all))
  #xy <- all[,c(9,8)]
  #print(all(xy))
  #spdf <- SpatialPointsDataFrame(coords=xy, data=all, proj4string=CRS("+proj=longlat +datum=WGS84 +no_defs"))
  #return(as.list(c(xy, spdf)))
  return(all)
}

#run the format_benton function on the Benton county files
Benton <- format_benton("Benton")

#combine the Posey and Benton county data
allsites <- rbind.data.frame(Posey, Benton)

#write function to format Gibson county data into format needed for appEEARS data download
format_gibson <-function(county){
  files <- list.files(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, sep="/"), pattern = "\\_Join.shp$")
  all <- data.frame()
  for (i in files){
    print(paste("now processing ",substr(i, 7, 16), sep=""))
    tst <- as.data.frame(shapefile(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, i, sep="/")))
    tst.shp <- shapefile(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, i, sep="/"))
    centers <- as.data.frame(gCentroid(tst.shp, byid = TRUE))
    tst <- cbind.data.frame(tst, centers)
    if (substr(i, 8, 13) == "Spring"){
      #tst <- tst[,c(1, 2, 4:11, 14:17)]
      tst <- tst[,c(4:7, 20, 19, 11, 14:17)]
      names(tst)[names(tst) == "y"] <- "R_Lat"
      names(tst)[names(tst) == "x"] <- "R_Lon"
      date <- sub(".*[_]([^.]+)[_].*", "\\1", i)
      tst$date <- rep(date, nrow= nrow(tst))
    } else {
      #tst <- tst[,c(1, 2, 4:11, 13:16)]
      tst <- tst[,c(4:7,19, 18, 11,13:16)]
      names(tst)[names(tst) == "y"] <- "R_Lat"
      names(tst)[names(tst) == "x"] <- "R_Lon"
      names(tst)[names(tst) == "Fall_Tilla"] <- "Tillage"
      date <- sub(".*[_]([^.]+)[_].*", "\\1", i) #get the date of the observations
      tst$date <- rep(date, nrow= nrow(tst))
    }
    all <- rbind.data.frame(all, tst)
  }
  #all <- all[all$R_Lon != 0,]
  all$site <- rep(county, nrow=nrow(all))
  print(head(all))
  #xy <- all[,c(9,8)]
  #print(all(xy))
  #spdf <- SpatialPointsDataFrame(coords=xy, data=all, proj4string=CRS("+proj=longlat +datum=WGS84 +no_defs"))
  #return(as.list(c(xy, spdf)))
  return(all)
}

#run the format_gibson function on the Gibson county files
Gibson <- format_gibson("Gibson")
#combine the Gibson data with the other counties
allsites <- rbind.data.frame(allsites, Gibson)

#define the function for Warren County
format_warren <-function(county){
  files <- list.files(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, sep="/"), pattern = "\\_join.shp$")
  all <- data.frame()
  for (i in files){
    print(paste("now processing ",substr(i, 8, 17), sep=""))
    tst <- as.data.frame(shapefile(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, i, sep="/")))
    tst.shp <- shapefile(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, i, sep="/"))
    centers <- as.data.frame(gCentroid(tst.shp, byid = TRUE))
    tst <- cbind.data.frame(tst, centers)
    if (substr(i, 8, 13) == "Spring"){
      #tst <- tst[,c(1, 2, 4:11, 14:16)]
      tst <- tst[,c(4:7, 20, 19, 11, 14:16)]
      tst$CC_Quality <- NA
      names(tst)[names(tst) == "y"] <- "R_Lat"
      names(tst)[names(tst) == "x"] <- "R_Lon"
      date <- sub(".*[_]([^.]+)[_].*", "\\1", i)
      tst$date <- rep(date, nrow= nrow(tst))
      
    } else {
      #tst <- tst[,c(1, 2, 4:11, 13:15)]
      tst <- tst[,c(4:7, 19, 18, 11, 13:16)]
      names(tst)[names(tst) == "Fall_Tilla"] <- "Tillage"
      names(tst)[names(tst) == "y"] <- "R_Lat"
      names(tst)[names(tst) == "x"] <- "R_Lon"
      date <- sub(".*[_]([^.]+)[_].*", "\\1", i) #get the date of the observations
      tst$date <- rep(date, nrow= nrow(tst))
    }
    all <- rbind.data.frame(all, tst)
  }
  #all <- all[all$R_Lon != 0,]
  all$site <- rep(county, nrow=nrow(all))
  print(head(all))
  #xy <- all[,c(9,8)]
  #print(all(xy))
  #spdf <- SpatialPointsDataFrame(coords=xy, data=all, proj4string=CRS("+proj=longlat +datum=WGS84 +no_defs"))
  #return(as.list(c(xy, spdf)))
  return(all)
}

#run the format_gibson function on the Gibson county files
Warren <- format_warren("Warren")
#Combine Warren county data with the other counties
allsites <- rbind.data.frame(allsites, Warren)

#define the function for White County
format_white <-function(county){
  files <- list.files(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, sep="/"), pattern = "\\_join.shp$")
  all <- data.frame()
  for (i in files){
    print(paste("now processing ",substr(i, 7, 16), sep=""))
    tst <- as.data.frame(shapefile(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, i, sep="/")))
    tst.shp <- shapefile(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, i, sep="/"))
    centers <- as.data.frame(gCentroid(tst.shp, byid = TRUE))
    tst <- cbind.data.frame(tst, centers)
    if (substr(i, 7, 12) == "Spring"){
      #tst <- tst[,c(2, 3, 5:11, 14, 17:19)]
      tst <- tst[,c(5:8, 23, 22, 14, 17:19)]
      names(tst)[names(tst) == "y"] <- "R_Lat"
      names(tst)[names(tst) == "x"] <- "R_Lon"
      tst$CC_Quality <- NA
      date <- sub(".*[_]([^.]+)[_].*", "\\1", i)
      tst$date <- rep(date, nrow= nrow(tst))
    } else {
      #tst <- tst[,c(2, 3, 5:11, 14, 16:18)]
      tst <- tst[,c(5:8, 22, 21, 14, 16:19)]
      names(tst)[names(tst) == "y"] <- "R_Lat"
      names(tst)[names(tst) == "x"] <- "R_Lon"
      names(tst)[names(tst) == "Fall_Tilla"] <- "Tillage"
      date <- sub(".*[_]([^.]+)[_].*", "\\1", i) #get the date of the observations
      tst$date <- rep(date, nrow= nrow(tst))
    }
    all <- rbind.data.frame(all, tst)
  }
  #all <- all[all$R_Lon != 0,]
  site <- substr(files[[1]], 1, 5)
  all$site <- rep(site, nrow=nrow(all))
  print(head(all))
  #xy <- all[,c(9,8)]
  #print(all(xy))
  #spdf <- SpatialPointsDataFrame(coords=xy, data=all, proj4string=CRS("+proj=longlat +datum=WGS84 +no_defs"))
  #return(as.list(c(xy, spdf)))
  return(all)
}

#run the format_gibson function on the Gibson county files
White <- format_white("White")
#names(White)[2] <- "type"

#Combine White county with data from the other counties
allsites <- rbind.data.frame(allsites, White)

write.csv(allsites, "C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/data/old_cos_surveydata_RandL.csv")

############################################################################################################
###########combine with the new counties (Summer 2021 analysis)#############################################
############################################################################################################
#function for Decatur, Hamilton, St Joseph, Washington, and Whitley counties
format_new <-function(county){
  files <- list.files(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, "Joined", sep="/"), pattern = ".shp$")
  files <- files[!grepl("fasp", files)]
  all <- data.frame()
  for (i in files){
    print(paste("now processing ",str_sub(i, -11, -5), sep=""))
    tst <- as.data.frame(shapefile(paste("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins", county, "Joined", i, sep="/")))
    season <- strsplit(i, "_") #get the season (fall/spring) of the observations
    season <- season[[c(1,2)]]
    if (season == "sp"){
      #tst <- tst[,c(13,6:9,11,12,17,20,21,22,24)]
      #tst <- tst[,c(6:9, 11, 12, 1, 20:22,24)]
      #tst <- tst[,c(13,6:9,11,12,17,20,21,22,23)] #for Whitley Co
      tst <- tst[,c(6:9, 11, 12, 1, 20:23)] #for Whitley Co with both R and L fields
      season[season == "sp"] <- "Spring"
      tst$date <- paste(season, tst$year_1, sep="")
    } else {
      #tst <- tst[,c(13,6:9,11,12,17,19,20,21,23)]
      #tst <- tst[,c(6:9, 11, 12, 1, 19:21, 23)]
      #tst <- tst[,c(13,6:9,11,12,17,19,20,21,22)] #for Whitley Co
      tst <- tst[,c(6:9, 11, 12, 1, 19:22)] #for Whitley Co with both R and L fields
      names(tst)[names(tst) == "falltillag"] <- "tillage"
      season[season == "fa"] <- "Fall"
      tst$date <- paste(season, tst$year_1, sep="")
    }
    all <- rbind.data.frame(all, tst)
  }
  all$site <- rep(county, nrow=nrow(all))
  print(head(all))
  #xy <- all[,c(9,8)]
  #print(all(xy))
  #spdf <- SpatialPointsDataFrame(coords=xy, data=all, proj4string=CRS("+proj=longlat +datum=WGS84 +no_defs"))
  #return(as.list(c(xy, spdf)))
  return(all)
}

#apply format_new to all of the counties included in the new (Summer 2021) analysis
Decatur <- format_new("Decatur")
names(Decatur)[names(Decatur) == "year_1"] <- "year"
Hamilton <- format_new("Hamilton")
Hamilton$date <- paste(Hamilton$date, Hamilton$year, sep="")
StJoe <- format_new("StJoseph")
StJoe$date <- paste(StJoe$date, StJoe$year, sep="")
Washington <- format_new("Washington")
Washington$date <- paste(Washington$date, Washington$year, sep="")
Whitley <- format_new("Whitley") #will need to change the column index values in the format_new function
names(Whitley)[names(Whitley) == "year_1"] <- "year"

new_cos <- rbind.data.frame(Decatur, Hamilton, StJoe, Washington, Whitley)

#load the old windshield survey data
old_cos <- read.csv("C:/Users/farellam/Documents/CoverCrops/data/old_cos_surveydata.csv")

#rename/remove columns as needed to allows for merging
names(new_cos)
names(old_cos)

names(new_cos)[names(new_cos) == "New_X"] <- "Long"
names(new_cos)[names(new_cos) == "New_Y"] <- "Lat"
#names(new_cos)[names(new_cos) == "new_ID"] <- "FID"
names(new_cos)[names(new_cos) == "tillage"] <- "Tillage"
names(new_cos)[names(new_cos) == "residue"] <- "Residue"
names(new_cos)[names(new_cos) == "covercrop"] <- "Cover_Crop"
#names(new_cos)[names(new_cos) == "fieldno"] <- "Field_No"
new_cos$CC_Quality <- NA
new_cos <- new_cos[ , !(names(new_cos) == "year")]

#names(old_cos)[names(old_cos) == "FID_"] <- "FID"
names(old_cos)[names(old_cos) == "R_Lat"] <- "Lat"
names(old_cos)[names(old_cos) == "R_Lon"] <- "Long"


#new_cos <- new_cos[,-12]
#old_cos <- old_cos[,-c(1,3,10)]

all <- rbind.data.frame(old_cos, new_cos)
write.csv(all, "C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/data/surveydata_RandL.csv")

############################################################################################################
###########process data for AppEEARS########################################################################
############################################################################################################
#For AppEEARS data needs to only contain lat, long and optional ID/Category columns
#delete rows with multiple observations for a single point
nodups <- all[!duplicated(all[,5:6]),]
#subset only, lat, long, field #, and site
final <- nodups[,c(13, 7, 5, 6)]
colnames(final) <- c("site", "Field_No", "Latitude", "Longitude")

new <- subset(final, site %in% c("Decatur", "Hamilton", "StJoseph", "Washington", "Whitley"))
final1 <- new[1:1000, ]
final2 <- new[1001:2000, ]
final3 <- new[2001:2242,]

write.csv(final1, "C:/Users/farellam/Documents/CoverCrops/appEEARS/appEEARS_newcos_sites1.csv")
write.csv(final2, "C:/Users/farellam/Documents/CoverCrops/appEEARS/appEEARS_newcos_sites2.csv")
write.csv(final3, "C:/Users/farellam/Documents/CoverCrops/appEEARS/appEEARS_newcos_sites3.csv")
write.csv(final, "C:/Users/farellam/Documents/CoverCrops/appEEARS//appEEARS_sites.csv")

#write a shapefile of the sample points
#read one of the county files for crs info
xx <- shapefile("C:/Users/farellam/OneDrive - Indiana University/Documents/CoverCrops/IN cover crop transect data/Buffer and transect data joins/Warren/Warren_Fall2016_join.shp")
mycrs <- crs(xx)
final_shp <- SpatialPointsDataFrame(final[,c(4,3)], final, proj4string = mycrs)
writeOGR(final_shp, "C:/Users/farellam/Documents/CoverCrops/data/spatial/sites.shp", layer="sites", driver = "ESRI Shapefile", overwrite_layer = TRUE)

#need to create a polygon for earthexplorer
#assign unique IDs to sample locations
final_shp$uniqueID <- seq(1, length(final_shp), by=1)
  #first create a bounding of the sample points
  poly_extent <- st_bbox(final_shp)
  #then transform the bounding box to a polygon
  sample_poly <- as(st_as_sfc(poly_extent, crs= crs(xx)), 'Spatial')
  sample_poly <- as(sample_poly, "SpatialPolygonsDataFrame")
writeOGR(sample_poly, "C:/Users/farellam/Documents/CoverCrops/data/spatial/sites_poly.shp", layer="sites_poly", driver = "ESRI Shapefile")
  
